---
# Useful default paths for config files on Mac/Linux platforms
__gitlab_runner_config_file_system_mode: /etc/gitlab-runner/config.toml
__gitlab_runner_config_file_user_mode: ~/.gitlab-runner/config.toml

gitlab_runner_registration_token_type: "authentication-token"
gitlab_runner_runners:
  - name: 'Docker GitLab Runner'
    token: 'glrt-KBaUl9RLG-UfXxhwRRGt_G86MQp0OjEKdToxCw.01.120voixcb'
    url: 'http://gitlab.hometask.xyz'
    request_concurrency: 2
    executor: docker
    docker_image: 'docker'
    tags:
      - shared
      - deploy
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_configs:
      runners.docker:
        extra_hosts: ["gitlab.hometask.xyz:192.168.122.1"]
