---
- name: "Restart_gitlab_runner"
  ansible.builtin.service:
    name: gitlab-runner
    state: "{{ gitlab_runner_restart_state }}"
  listen: restart_gitlab_runner
  become: true
  when: ansible_facts['os_family'] != 'Darwin' and ansible_facts['os_family'] != 'Windows' and not gitlab_runner_container_install
