stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - set -e
    - docker compose down -v
    - docker compose up -d --build
    - docker compose ps
    - docker image prune -f
  only:
    - main
